config/routes.rb
UrlShortener::Application.routes.draw do
  root :to => "Urls#new"

  get "/url/:uid", :to => "Urls#show", :as => :url
  post "/url/new", :to => "Urls#create", :as => :new_url
  get "/:uid", :to => "Urls#expand", :as => :expand
end

app/models/url.rb
class Url < ActiveRecord::Base
  BASE = 36

  attr_accessible :url

  validates_format_of :url, :with => URI::regexp(%w(http https))

  def uid
    id.to_s(BASE) if persisted?
  end

  def self.find_by_uid!(uid)
    find uid.to_i(BASE)
  end

  def to_param
    uid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  private

  def not_found
    render :file => Rails.root.join("public/404.html"),
      :status => :not_found
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def show
    @url = Url.find_by_uid!(params[:uid])
  end

  def new
    @url = Url.new
  end

  def create
    @url = UrlCreator.create(params[:url])

    if @url.persisted?
      redirect_to url_path(@url), :notice => t("flash.urls.create.notice")
    else
      render :new
    end
  end

  def expand
    @url = Url.find_by_uid!(params[:uid])
    redirect_to @url.url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_errors(record)
    FormErrors.new(record).render(self)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/flash_messages" %>

<%= yield %>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <p class="<%= type %>">
    <%= message %>
  </p>
<% end %>

app/views/shared/_form_errors.html.erb
<p>
  <%= t("form.error_message") %>
</p>

<ul>
  <% errors.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

app/views/urls/new.html.erb
<%= form_errors(@url) %>

<%= form_for @url, :url => new_url_path do |f| %>
  <p>
    <%= f.label :url, t("form.labels.url.url") %>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/urls/show.html.erb
<p>
  Your shortened url is <strong><%= expand_url(@url) %></strong>
</p>

<p>
  <%= link_to t("actions.visit"), expand_url(@url) %>
</p>